sudo: false
language: go
go:
  - 1.4.1
install:
  - go get -v -t ./...
  - go get -v github.com/onsi/ginkgo/ginkgo
script:
  - ginkgo -r -race -failOnPending -randomizeAllSpecs
branches:
  only:
  - master
